version: '3.8'

services:
  app:
    build: .
    container_name: tiktok_app
    restart: always

  nginx:
    image: nginx:latest
    container_name: tiktok_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
